spring: 
  application: 
    name: meetup-gateway-service
  h2:
    console:
      enabled: true
      
security:
  basic:
    enabled: false
    
server:
  port: 8888
    
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-f560953d-50b5-49e9-8105-13ad19ccef34.cfapps.io